version: '3.0'

services:

  gobimport:
    build: src
    container_name: gobimport
    environment:
      MESSAGE_BROKER_ADDRESS: rabbitmq
      GOB_SHARED_DIR: /app/shared
      PREPARE_DATABASE_PORT_OVERRIDE: 5432
      PREPARE_DATABASE_HOST_OVERRIDE: prepare_database
      BAGEXTRACT_DATABASE_PORT_OVERRIDE: 5432
      BAGEXTRACT_DATABASE_HOST_OVERRIDE: bagextract_database
      SECURE_SALT: insecure
      SECURE_PASSWORD: insecure
      GOB_IMPORT_DATABASE_HOST: gobimport_database
      GOB_IMPORT_DATABASE_PORT: 5432
    env_file: .env
    volumes:
      - gob-volume:/app/shared
    depends_on:
      - gobimport_database

  gobimport_database:
    image: amsterdam/postgres11
    ports:
      - "5412:5432"
    container_name: gobimport_database
    environment:
      POSTGRES_PASSWORD: insecure
      POSTGRES_DB: gob_import
      POSTGRES_USER: gob_import
    volumes:
      - "~/.ssh/datapunt.key:/root/.ssh/datapunt.key"
    shm_size: '1gb'

volumes:
  gob-volume:
    external: true


networks:
  default:
    external:
      name: gob-network
