version: '3.0'

services:

  gobimport:
    build: src
    container_name: gobimport
    environment:
      MESSAGE_BROKER_ADDRESS: rabbitmq
      GOB_SHARED_DIR: /app/shared
    env_file: .env
    volumes:
      - gob-volume:/app/shared

volumes:
  gob-volume:
    external: true


networks:
  default:
    external:
      name: gob-network
