version: "3.7"

services:

  gobimport:
    build:
      context: src
      target: development
    container_name: gobimport
    image: gob_import
    environment:
      MESSAGE_BROKER_ADDRESS: rabbitmq
      GOB_SHARED_DIR: /app/shared
      PREPARE_DATABASE_PORT_OVERRIDE: 5432
      PREPARE_DATABASE_HOST_OVERRIDE: prepare_database
      BAGEXTRACT_DATABASE_PORT_OVERRIDE: 5432
      BAGEXTRACT_DATABASE_HOST_OVERRIDE: bagextract_database
      SECURE_SALT: insecure
      SECURE_PASSWORD: insecure
    env_file: .env
    volumes:
      - gob-volume:/app/shared
      - ./src/gobimport:/app/gobimport
      - ./src/tests:/app/tests
      - ${GOB_CORE_DIR-../GOB-Core}:/app/GOB-Core
      - ${GOB_CONFIG_DIR-../GOB-Config}:/app/GOB-Config


volumes:
  gob-volume:
    external: true


networks:
  default:
    name: gob-network
    external: true
