"""Add MutationImport model

Revision ID: 8a5295fa3641
Revises:
Create Date: 2021-02-04 14:10:49.026184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a5295fa3641'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'mutation_import',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('catalogue', sa.String(), nullable=True),
        sa.Column('collection', sa.String(), nullable=True),
        sa.Column('application', sa.String(), nullable=True),
        sa.Column('started_at', sa.DateTime(), nullable=True),
        sa.Column('ended_at', sa.DateTime(), nullable=True),
        sa.Column('filename', sa.String(), nullable=True),
        sa.Column('mode', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mutation_import_application'), 'mutation_import', ['application'], unique=False)
    op.create_index(op.f('ix_mutation_import_catalogue'), 'mutation_import', ['catalogue'], unique=False)
    op.create_index(op.f('ix_mutation_import_collection'), 'mutation_import', ['collection'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mutation_import_collection'), table_name='mutation_import')
    op.drop_index(op.f('ix_mutation_import_catalogue'), table_name='mutation_import')
    op.drop_index(op.f('ix_mutation_import_application'), table_name='mutation_import')
    op.drop_table('mutation_import')
    # ### end Alembic commands ###
